export type MitreDifficulty = "beginner" | "intermediate" | "advanced" | "expert";

export interface MitreTechnique {
  id: string;
  name: string;
  tactic: string;
  description: string;
  difficulty: MitreDifficulty;
  requires: string[];
  indicators: string[];
  procedures: string[];
}

/** Curated MITRE ATT&CK-style techniques for SentinelForge simulations (30+). */
export const MITRE_TECHNIQUES: MitreTechnique[] = [
  {
    id: "T1566.001",
    name: "Spearphishing Attachment",
    tactic: "Initial Access",
    description: "Adversary sends a malicious attachment to gain initial foothold.",
    difficulty: "beginner",
    requires: [],
    indicators: ["email_attachment.exe", "macro_enabled_doc"],
    procedures: ["Send crafted .docm with VBA macro", "ISO + LNK combo"],
  },
  {
    id: "T1190",
    name: "Exploit Public-Facing Application",
    tactic: "Initial Access",
    description: "Exploit a vulnerability in an Internet-facing service.",
    difficulty: "intermediate",
    requires: [],
    indicators: ["unexpected_waf_bypass", "deserialization_gadget"],
    procedures: ["SQLi to RCE chain", "OGNL injection on Java app"],
  },
  {
    id: "T1078",
    name: "Valid Accounts",
    tactic: "Initial Access",
    description: "Use stolen or default credentials for access.",
    difficulty: "beginner",
    requires: [],
    indicators: ["auth_success_off_hours", "shared_service_account"],
    procedures: ["Password spray", "Pass-the-hash reuse"],
  },
  {
    id: "T1059.001",
    name: "PowerShell",
    tactic: "Execution",
    description: "Execute commands via PowerShell.",
    difficulty: "beginner",
    requires: ["T1078"],
    indicators: ["encodedcommand", "bypass_amsi_strings"],
    procedures: ["Download cradle IEX", "Invoke-Expression obfuscation"],
  },
  {
    id: "T1059.004",
    name: "Unix Shell",
    tactic: "Execution",
    description: "Shell command execution on Linux/Unix.",
    difficulty: "beginner",
    requires: ["T1190"],
    indicators: ["/bin/bash -c curl", "nohup payload.sh"],
    procedures: ["Reverse shell one-liner", "chmod +x dropper"],
  },
  {
    id: "T1053.005",
    name: "Scheduled Task",
    tactic: "Execution",
    description: "Abuse task scheduler for execution.",
    difficulty: "intermediate",
    requires: ["T1059.001"],
    indicators: ["schtasks_create", "task_xml_hidden"],
    procedures: ["ONLOGON trigger", "SYSTEM context task"],
  },
  {
    id: "T1047",
    name: "Windows Management Instrumentation",
    tactic: "Execution",
    description: "Use WMI for execution and lateral movement prep.",
    difficulty: "intermediate",
    requires: ["T1059.001"],
    indicators: ["wmic_process_call_create", "root\\\\subscription"],
    procedures: ["Remote WMI class execution", "WMI event consumer"],
  },
  {
    id: "T1547.001",
    name: "Registry Run Keys",
    tactic: "Persistence",
    description: "Persist via Run/RunOnce registry keys.",
    difficulty: "beginner",
    requires: ["T1059.001"],
    indicators: ["HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run"],
    procedures: ["regsvr32 sideload", "Startup persistence"],
  },
  {
    id: "T1136.001",
    name: "Local Account",
    tactic: "Persistence",
    description: "Create a local account for persistence.",
    difficulty: "intermediate",
    requires: ["T1078"],
    indicators: ["net_user_add", "odd_local_admin"],
    procedures: ["net user svc_ops /add", "clone guest SID patterns"],
  },
  {
    id: "T1098",
    name: "Account Manipulation",
    tactic: "Persistence",
    description: "Modify accounts to maintain access.",
    difficulty: "advanced",
    requires: ["T1136.001"],
    indicators: ["group_membership_change", "shadow_admin"],
    procedures: ["Add user to Enterprise Admins", "ACL tampering"],
  },
  {
    id: "T1068",
    name: "Exploitation for Privilege Escalation",
    tactic: "Privilege Escalation",
    description: "Exploit OS/app bugs to elevate privileges.",
    difficulty: "advanced",
    requires: ["T1059.004"],
    indicators: ["suid_binary_abuse", "kernel_exploit_dmesg"],
    procedures: ["CVE-2021-3156 sudo", "Dirty pipe style chain"],
  },
  {
    id: "T1055.012",
    name: "Process Hollowing",
    tactic: "Privilege Escalation",
    description: "Inject code into a suspended legitimate process.",
    difficulty: "expert",
    requires: ["T1059.001"],
    indicators: ["image_load_mismatch", "hollowed_svchost"],
    procedures: ["CreateProcess suspended + NtUnmapViewOfSection"],
  },
  {
    id: "T1027",
    name: "Obfuscated Files or Information",
    tactic: "Defense Evasion",
    description: "Hide payloads via encoding/packing.",
    difficulty: "intermediate",
    requires: ["T1059.004"],
    indicators: ["base64_layers", "packed_elf_entropy"],
    procedures: ["shc compiled dropper", "XOR staged loader"],
  },
  {
    id: "T1070.001",
    name: "Clear Windows Event Logs",
    tactic: "Defense Evasion",
    description: "Delete or clear security logs.",
    difficulty: "advanced",
    requires: ["T1059.001"],
    indicators: ["wevtutil_cl", "security_log_gap"],
    procedures: ["wevtutil cl Security", "Stop EventLog service"],
  },
  {
    id: "T1036.005",
    name: "Match Legitimate Name",
    tactic: "Defense Evasion",
    description: "Masquerade malware as trusted binaries.",
    difficulty: "intermediate",
    requires: ["T1059.004"],
    indicators: ["/tmp/kworker", "misspelled_system_binary"],
    procedures: ["Rename to crond", "PATH hijack"],
  },
  {
    id: "T1003.001",
    name: "LSASS Memory",
    tactic: "Credential Access",
    description: "Dump credentials from LSASS.",
    difficulty: "advanced",
    requires: ["T1068"],
    indicators: ["comsvcs_minidump", "procdump_lsass"],
    procedures: ["rundll32 comsvcs MiniDump", "SilentProcessExit"],
  },
  {
    id: "T1110.001",
    name: "Password Guessing",
    tactic: "Credential Access",
    description: "Brute force authentication.",
    difficulty: "beginner",
    requires: ["T1190"],
    indicators: ["auth_fail_burst", "hydra_like_patterns"],
    procedures: ["SSH spray", "RDP password guessing"],
  },
  {
    id: "T1558.003",
    name: "Kerberoasting",
    tactic: "Credential Access",
    description: "Request service tickets and crack offline.",
    difficulty: "expert",
    requires: ["T1078"],
    indicators: ["rc4_hmac_tgs", "spn_scan"],
    procedures: ["GetUserSPNs.py", "Rubeus kerberoast"],
  },
  {
    id: "T1087.001",
    name: "Local Account Discovery",
    tactic: "Discovery",
    description: "Enumerate local accounts.",
    difficulty: "beginner",
    requires: ["T1059.004"],
    indicators: ["cat_etc_passwd", "getent_passwd"],
    procedures: ["id -Gn", "ldapsearch anonymous"],
  },
  {
    id: "T1046",
    name: "Network Service Scanning",
    tactic: "Discovery",
    description: "Scan internal services for lateral targets.",
    difficulty: "beginner",
    requires: [],
    indicators: ["nmap_syn_scan", "masscan_signature"],
    procedures: ["nmap -sS", "nc port sweep"],
  },
  {
    id: "T1083",
    name: "File and Directory Discovery",
    tactic: "Discovery",
    description: "Discover sensitive files for staging.",
    difficulty: "beginner",
    requires: ["T1087.001"],
    indicators: ["find_world_writable", "grep_secret_keywords"],
    procedures: ["find / -perm -4000", "grep -R password"],
  },
  {
    id: "T1021.001",
    name: "Remote Desktop Protocol",
    tactic: "Lateral Movement",
    description: "Move laterally using RDP.",
    difficulty: "intermediate",
    requires: ["T1078", "T1046"],
    indicators: ["rdp_client_ip_internal", "mstsc_cache"],
    procedures: ["RDP with stolen creds", "Clipboard exfil"],
  },
  {
    id: "T1210",
    name: "Exploitation of Remote Services",
    tactic: "Lateral Movement",
    description: "Exploit remote service for lateral movement.",
    difficulty: "advanced",
    requires: ["T1021.001"],
    indicators: ["eternalblue_like_msrpc", "smb_pipe_anomaly"],
    procedures: ["MS-RPC exploit chain", "WMI lateral exec"],
  },
  {
    id: "T1005",
    name: "Data from Local System",
    tactic: "Collection",
    description: "Collect files from compromised host.",
    difficulty: "beginner",
    requires: ["T1083"],
    indicators: ["tar_cf_staging", "recursive_copy_sensitive"],
    procedures: ["tar czf /tmp/staging.tgz", "robocopy mirrors"],
  },
  {
    id: "T1074.001",
    name: "Local Data Staging",
    tactic: "Collection",
    description: "Stage collected data prior to exfiltration.",
    difficulty: "intermediate",
    requires: ["T1005"],
    indicators: ["/tmp/staging", "hidden_dir_dot_prefix"],
    procedures: ["mkdir /tmp/staging", "chmod 777 staging"],
  },
  {
    id: "T1113",
    name: "Screen Capture",
    tactic: "Collection",
    description: "Capture screen contents.",
    difficulty: "intermediate",
    requires: ["T1059.001"],
    indicators: ["screenshot_api_calls", "desktop_png_drop"],
    procedures: ["GDI BitBlt capture", "PowerShell screenshot"],
  },
  {
    id: "T1041",
    name: "Exfiltration Over C2 Channel",
    tactic: "Exfiltration",
    description: "Exfiltrate data over existing C2.",
    difficulty: "advanced",
    requires: ["T1074.001"],
    indicators: ["dns_txt_chunks", "beacon_jitter"],
    procedures: ["DNS TXT staging", "HTTPS POST exfil"],
  },
  {
    id: "T1567.002",
    name: "Exfiltration to Cloud Storage",
    tactic: "Exfiltration",
    description: "Upload stolen data to cloud file storage.",
    difficulty: "intermediate",
    requires: ["T1074.001"],
    indicators: ["s3_put_object_burst", "oauth_token_abuse"],
    procedures: ["aws s3 cp /tmp/staging", "rclone to MEGA"],
  },
  {
    id: "T1486",
    name: "Data Encrypted for Impact",
    tactic: "Impact",
    description: "Encrypt data for ransomware impact.",
    difficulty: "advanced",
    requires: ["T1005"],
    indicators: ["readme_txt_ransom", "vssadmin_delete_shadows"],
    procedures: ["ChaCha20 file encryption", "delete shadow copies"],
  },
  {
    id: "T1490",
    name: "Inhibit System Recovery",
    tactic: "Impact",
    description: "Disable backups and recovery options.",
    difficulty: "intermediate",
    requires: ["T1486"],
    indicators: ["wbadmin_delete_catalog", "bcdedit_recoveryenabled_off"],
    procedures: ["vssadmin delete shadows", "wbadmin delete catalog"],
  },
  {
    id: "T1566",
    name: "Phishing",
    tactic: "Initial Access",
    description: "Phishing umbrella technique.",
    difficulty: "beginner",
    requires: [],
    indicators: ["suspicious_sender_domain", "html_smuggling"],
    procedures: ["Credential harvesting page", "OAuth consent phishing"],
  },
  {
    id: "T1059",
    name: "Command and Scripting Interpreter",
    tactic: "Execution",
    description: "Generic interpreter abuse.",
    difficulty: "beginner",
    requires: ["T1566"],
    indicators: ["cmd.exe_children", "powershell_encoded"],
    procedures: ["cmd /c bitsadmin", "wscript cscript chains"],
  },
  {
    id: "T1547",
    name: "Boot or Logon Autostart Execution",
    tactic: "Persistence",
    description: "Autostart execution persistence.",
    difficulty: "intermediate",
    requires: ["T1059"],
    indicators: ["startup_folder_lnk", "com_hijack"],
    procedures: ["Startup Approved Run", "COM hijack in HKCU"],
  },
  {
    id: "T1055",
    name: "Process Injection",
    tactic: "Privilege Escalation",
    description: "Inject into another process.",
    difficulty: "expert",
    requires: ["T1059"],
    indicators: ["open_process_vm_write", "queue_apc_injection"],
    procedures: ["DLL injection", "APC queue"],
  },
  {
    id: "T1070",
    name: "Indicator Removal",
    tactic: "Defense Evasion",
    description: "Remove forensic indicators.",
    difficulty: "advanced",
    requires: ["T1027"],
    indicators: ["log_cleared", "timestomp_mtim"],
    procedures: ["shred -u logs", "touch -r reference"],
  },
  {
    id: "T1036",
    name: "Masquerading",
    tactic: "Defense Evasion",
    description: "Masquerade as legitimate entity.",
    difficulty: "intermediate",
    requires: ["T1059.004"],
    indicators: ["wrong_path_execution", "signed_binary_proxy"],
    procedures: ["LOLBins rename", "squiblytwo"],
  },
  {
    id: "T1003",
    name: "OS Credential Dumping",
    tactic: "Credential Access",
    description: "Dump OS-stored credentials.",
    difficulty: "advanced",
    requires: ["T1068"],
    indicators: ["/etc/shadow_read", "mimikatz_like_strings"],
    procedures: ["shadow copy LSASS", "secretsdump"],
  },
  {
    id: "T1110",
    name: "Brute Force",
    tactic: "Credential Access",
    description: "Credential brute forcing.",
    difficulty: "beginner",
    requires: ["T1046"],
    indicators: ["ssh_auth_failures", "winrm_401_burst"],
    procedures: ["medusa hydra patterns", "Kerberos preauth spray"],
  },
  {
    id: "T1558",
    name: "Steal or Forge Kerberos Tickets",
    tactic: "Credential Access",
    description: "Abuse Kerberos tickets.",
    difficulty: "expert",
    requires: ["T1078"],
    indicators: ["golden_ticket_anomaly", "krbtgt_rc4"],
    procedures: ["Mimikatz golden ticket", "Silver ticket to service"],
  },
  {
    id: "T1087",
    name: "Account Discovery",
    tactic: "Discovery",
    description: "Discover accounts in environment.",
    difficulty: "beginner",
    requires: ["T1046"],
    indicators: ["net_user_domain_admins", "ldap_enum_users"],
    procedures: ["net group /domain", "ldapdomaindump"],
  },
  {
    id: "T1021",
    name: "Remote Services",
    tactic: "Lateral Movement",
    description: "Abuse remote services generically.",
    difficulty: "intermediate",
    requires: ["T1003"],
    indicators: ["smb_admin_share_ipc", "winrm_remote_shell"],
    procedures: ["PsExec", "evil-winrm"],
  },
];

const byId = new Map(MITRE_TECHNIQUES.map((t) => [t.id, t]));

export function getMitreTechnique(id: string): MitreTechnique | undefined {
  return byId.get(id);
}

export function resolveScenarioTechniqueIds(mitreField: string): string[] {
  const parts = mitreField.split(/[,;\s]+/).map((s) => s.trim()).filter(Boolean);
  const resolved: string[] = [];
  for (const p of parts) {
    const exact = byId.get(p);
    if (exact) {
      resolved.push(exact.id);
      continue;
    }
    const match = MITRE_TECHNIQUES.find((t) => t.id.startsWith(p) || p.startsWith(t.id.split(".")[0] ?? ""));
    if (match) resolved.push(match.id);
  }
  return [...new Set(resolved)];
}
